---
 - hosts: webservers
   connection: local
   gather_facts: no
   tasks:
   - name: Get hostname
     shell: echo $HOSTNAME
     register: result

   - name: Print the var
     debug:
       var: result


   - name: Get uptime first
     shell: uptime
     register: hello
   - debug: msg="{{ hello.stdout }}"
   - debug: msg="{{ hello.stderr }}"

   - name: Get date second
     shell: date
     register: hello
   - debug: msg="{{ hello.stdout }}"
   - debug: msg="{{ hello.stderr }}"


   - name: crear carpeta de scripts
     file:
       path: /home/ansible/playbook-aj/ansible-playbooks-demo
       state: directory

   - name: copiar el script
     copy:
       src: /home/ansible/playbook-aj/ansible-playbooks-demo/servicios.sh
       dest: /home/ansible/playbook-aj/servicios.sh

   - name: ejecutar script como sudo
     become: yes
     script: /home/ansible/playbook-aj/servicios.sh












